// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPC_sevice.proto

package com.example.grpc;

public final class GRPCSevice {
  private GRPCSevice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gRPC_sevice.proto\032\nuser.proto\032\020calcula" +
      "tor.proto2r\n\013grpcservice\022$\n\005login\022\r.Logi" +
      "nRequest\032\014.APIResponse\022\036\n\006logout\022\006.Empty" +
      "\032\014.APIResponse\022\035\n\004math\022\014.calculation\032\007.R" +
      "esultB\024\n\020com.example.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.grpc.User.getDescriptor(),
          com.example.grpc.Calculator.getDescriptor(),
        }, assigner);
    com.example.grpc.User.getDescriptor();
    com.example.grpc.Calculator.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
